# Generated by Django 4.1.4 on 2022-12-31 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('sdesc', models.TextField()),
                ('ldesc', models.TextField()),
                ('quantity', models.CharField(max_length=100)),
                ('slug', models.BooleanField(default=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.categories')),
            ],
        ),
    ]
