# Generated by Django 4.1.4 on 2022-12-31 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0003_product_active_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(null=True, upload_to='product_others/images/')),
                ('active', models.BooleanField(default=True)),
                ('single_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom_app.product')),
            ],
        ),
    ]
